<?php
  	include_once('src/models/Masterfile.php');
  	$mf = new Masterfile();
  
	set_title('Add Masterfile');
	set_layout('wizard_layout.php');
?>
<div class="page-title">
  <div class="title_left">
    <h3>Add Masterfile</h3>
  </div>

  <?php include('src/search_box.php'); ?>
</div>
<div class="clearfix"></div>

<div class="row">

  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2><i class="glyphicon glyphicon glyphicon-user"></i> Registration</h2>
        
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <?php 
          $mf->splash('masterfile'); 
          if(isset($_SESSION['warnings']))
            $mf->displayWarnings('warnings');
        ?>
        <form action="" method="post" novalidate enctype="multipart/form-data" id="add_masterfile">
        <!-- Smart Wizard -->
        <p>
        <ul>
        	<li><i>This wizard can be used to register Students, Staff, Subordinate Staff, Parent/Guardian e.t.c.</i></li>
        	<li><i>Every user will be required to change his/her password when he or she logs in for the first time.</i></li>
          <li><i>Please copy the autogenerated password since that is what will be required for logging in the first time.</i></li>
          <li><i>Please ensure that you fill in all the fields marked with an asteric(*).</i></li>
        </ul>
        </p>

        <div id="wizard" class="form_wizard wizard_horizontal">
          <ul class="wizard_steps">
            <li>
              <a href="#step-1">
                <span class="step_no">1</span>
                <span class="step_descr">
                  Step 1<br />
                  <small>Step 1 Personal Details</small>
              </span>
              </a>
            </li>
            <li>
              <a href="#step-2">
                <span class="step_no">2</span>
                <span class="step_descr">
                    Step 2<br />
                    <small>Step 2 Contact Details</small>
                </span>
              </a>
            </li>
            <li>
              <a href="#step-3">
                <span class="step_no">3</span>
                <span class="step_descr">
                    Step 3<br />
                    <small>Step 3 Login Details</small>
                </span>
              </a>
            </li>
            
          </ul>

          
          <div id="step-1">
          <?php include('personal_details.php'); ?>
          </div>
          <div id="step-2">
           <?php include('address_details.php'); ?>
          </div>
          <div id="step-3">
            <?php include('login_details.php'); ?>
          </div>

        </div>
        <!-- End SmartWizard Content -->
        </form>
      </div>
    </div>
  </div>
</div>
<?php set_js(array('src/js/masterfile.js')); ?>